### ISSUE TITLE
please delete this issue

### ISSUE THREAD

**Issue by fredfalcon** [hblankenship/admin-local-go#2]
"github.WeeklyCommitActivity{Days:[0 3 0 0 0 0 0], Total:3, Week:github.Timestamp{2022-03-26 19:00:00 -0500 CDT}}
"

**Comment by johnnyjeannatasha** [comment]
> "github.WeeklyCommitActivity{Days:[0 3 0 0 0 0 0], Total:3, Week:github.Timestamp{2022-03-26 19:00:00 -0500 CDT}}
> "

Ive been working on this for the least almost a month.
